### ISSUE TITLE
Complete OPORD and GM document

### ISSUE THREAD

**Issue by jerkinmerkin** [Task-Force-Red/Operation-Python#1]
Complete OPORD and create a GM document.

WIP documentation: https://docs.google.com/document/d/15qS9cbq9GYyPQn5nODoHRIbVG4bu7av_E00UF8-8LGk

**Comment by Will-Nichols** [comment]
You need some help with this or do you have any thing else that needs to be tweaked or adjusted?

**Comment by jerkinmerkin** [comment]
GM doc is done I just gotta complete the OPORD

**Comment by Will-Nichols** [comment]
Also might want to reupload your mission stuff here to the GitHub...just saying.

**Comment by jerkinmerkin** [comment]
Completed... and stuff re-uploaded.
