### ISSUE TITLE
"Error in expression" for intel script

### ISSUE THREAD

**Issue by jerkinmerkin** [Task-Force-Red/Operation-Python#11]
@Jmaster9999, this is your territory.  I have three different "intel" scripts I'm using to script intel conversations.  They are exactly the same except the conversations are different and they're renamed in order.  civIntel & civIntel2 work just fine.  civIntel3 is throwing up this error when I attempt to use it:

20:29:52 Error in expression <call  civ_startAsk_intel_3>
20:29:52   Error position: <civ_startAsk_intel_3>
20:29:52   Error Undefined variable in expression: civ_startask_intel_3

Link to script: [https://drive.google.com/file/d/1v9IYuA21NanT16buuthj1N4fP2sjCYmR/view?usp=sharing](url)

I'm using this in unit init:  [blue6,["Talk to CO",{call  civ_startAsk_intel_3}]]remoteExec["addAction",0];

and in init.sqf: #include"common\server\civ\civIntel3.sqf";

**Comment by Jmaster9999** [comment]
Hopefully fixed?

**Comment by jerkinmerkin** [comment]
Intel3 still doesn't work, but I'm no longer getting that script error popping up.  Intel1 & 2 still work tho.

**Comment by jerkinmerkin** [comment]
Yea this is weird.  There is nothing in the RPT now and the action doesn't do anything.. but the other two scripts still work fine.

**Comment by jerkinmerkin** [comment]
@Jmaster9999 here's an idea.  the original script was meant for civs, so all the actions call _civ on it.  I want to work with a blufor unit, so I changed all _civ to _unit.  Could that be breaking it as well?

**Comment by jerkinmerkin** [comment]
Okay, so it does work with civs.  Thanks @Jmaster9999 that actually did fix it when it comes to civs.  Now would you know how to edit this script so it works with non-civ units as well?

**Comment by jerkinmerkin** [comment]
I have a work-around.  If I set the blufor unit captive he's transformed to a civ and the script works.  Unfortunately, this means that because hes a civ, he cowers he fear and runs away at the sound of gunfire due to another script.  The only way to make this work is take the "Intel" script can change it from civ to unit or blufor or whatever without it breaking.

**Comment by jerkinmerkin** [comment]
Oh shit, I got it to work!  Team effort by @Jmaster9999 and myself.  Case closed!
