### ISSUE TITLE
Test and implement MRH Satellite mod for the mission.

### ISSUE THREAD

**Issue by Jebudiah** [Task-Force-Red/Operation-Python#12]
As the title says, implement the Satellite mod into the mission and give it to SOG elements for use in the field.

Make certain it works with ALiVE virtualization.

**Comment by Will-Nichols** [comment]
I have tested it extensively with[ Operation Jungle Vengenance](https://github.com/Task-Force-Red/Operation-Jungle-Vengeance) and its an easily setup and working mod. The primary thing to do is make sure you use something like the monitors or laptops to allow you to see what you need to see at the control stations/base areas.

**Comment by jerkinmerkin** [comment]
Ah okay I've taken a look at this.  This is cool. as. fuck.  I would like to write a config so that I can make a USM alice backpack the satellite backpack instead of the vanilla Arma 3 Carryall.

**Comment by Will-Nichols** [comment]
I don't have the backpacks in game. I have it setup with tablets, monitors and laptops which I think you can put in backpacks.

**Comment by jerkinmerkin** [comment]
Yea i just found out you can use an antenna item instead of a whole backpack.  No need for configs.

**Comment by jerkinmerkin** [comment]
Okay, so I've put it in the mission.  Here's some limitations.  Satellite does NOT spawn virtualized units.  Same goes for fen_ais objects.  I can probably remove the fen_ais object modules as long as I disable simulation, but there still won't be any virtualized units spawned in.  Thoughts?

**Comment by Will-Nichols** [comment]
I have not worried about it not spawning in units. I find that to be a benefit instead of a limitation. If we want to spawn stuff in then we could simply have the GM hover over the a couple of minutes before the satellite sweeps over the area to simulate the look from on high.

**Comment by jerkinmerkin** [comment]
Yea thats fine with me.  What I will do tho is remove all the fen_ais object modules so that the satellite can better spot enemy camps and bunkers.  If most or all the objects have simulation turned off or simple object there should be too much of a performance hit, corrcet @Jmaster9999 ?
