### ISSUE TITLE
Add script to convert BI arsenal boxes to ACE arsenal boxes

### ISSUE THREAD

**Issue by jerkinmerkin** [Task-Force-Red/Operation-Python#13]
@Jmaster9999, send me the script please.

**Comment by Jmaster9999** [comment]
https://forums.bohemia.net/forums/topic/213126-ace-version-3120-arsenal/?do=findComment&comment=3283548

**Comment by Jmaster9999** [comment]
`_stuff = [];
_functions = [BIS_fnc_getVirtualBackpackCargo,BIS_fnc_getVirtualItemCargo,BIS_fnc_getVirtualMagazineCargo,BIS_fnc_getVirtualWeaponCargo];
{
    _things = ammobox call _x;
    _stuff = _stuff + _things;
} forEach _functions;
_init = format ["[this,%1] call ace_arsenal_fnc_initBox;",_stuff];
copyToClipboard _init;`

**Comment by Jmaster9999** [comment]
To get it to work: Name the box "ammobox", then run that code in the debug console in the editor. Then paste the formated code into the init field of the box. Repeat for each ammo box on the map.

**Comment by jerkinmerkin** [comment]
Done.
