### ISSUE TITLE
Infantry Arsenal object replacement // Infantry arsenal update

### ISSUE THREAD

**Issue by Jebudiah** [Task-Force-Red/Operation-Python#19]
The object being used as the ACE arsenal in the Infantry hangar is too large to access the ACE options except for the very front of the object, it would be impossible for multiple people to interact with it at the same time easily.

Also, the arsenal only has an M4 in it when I interacted with it. The arsenal either needs to contain all of the infantry weapons in the event weapons need to be traded out, or it needs to have loadouts for the different infantry roles saved in the Public Loadouts section of the ACE arsenal.

**Comment by jerkinmerkin** [comment]
FYI, it appears that the script which converts BI arsenal to Ace arsenal and the script that adds the scroll wheel option are incompatible.  The boxes also need to have simulation enabled but I think there's a script which turns R3F logistics off on the object.  I'll have to go in and redo the arsenal in the editor.  Just thought I'd let you all know for future missions.

**Comment by Jmaster9999** [comment]
I got a script that adds the schrool wheel back. I added it in my edits

**Comment by jerkinmerkin** [comment]
Done.
