### ISSUE TITLE
TFRed_AdminTools alongside MCC?

### ISSUE THREAD

**Issue by Will-Nichols** [Task-Force-Red/Operation-Python#41]
Was looking at the file on the server and saw that was in there. Are you still using that or did you pull it off for MCC? Also I have an MCC Array setup already if you need it for the module to create that for the GM/admin folks.

**Comment by jerkinmerkin** [comment]
I mean if we don’t need the admin tools I can remove them.

**Comment by Will-Nichols** [comment]
All they do is give access without having to put down any Zeus modules for the people who will be the GM/admins.

**Comment by jerkinmerkin** [comment]
Ah okay.  Seems kinda redundant then cause I already put down the modules.

**Comment by jerkinmerkin** [comment]
I can remove the tools to shrink the mission file.  Speaking of which I’ll remove some of the sounds I’m not using since auburn said it was cool

**Comment by Will-Nichols** [comment]
Will close this one then.
