### ISSUE TITLE
Move Infanry spawn point

### ISSUE THREAD

**Issue by jerkinmerkin** [Task-Force-Red/Operation-Python#6]
I made all these cool spawn points for all groups except infantry, who I just had spawning in the barracks.  I don’t want to leave anyone out so I plan on moving them to a hanger and making their own little immersive spawn area.

**Comment by Scotty-Z** [comment]
working on this

**Comment by Scotty-Z** [comment]
@jerkinmerkin finished

**Comment by jerkinmerkin** [comment]
Cool, make sure it’s a separate mission file with just the infantry hanger stuff so I can merge the mission files tomorrow.

**Comment by jerkinmerkin** [comment]
@Scotty-Z that's perfect... exactly how I envisioned it!  Merged with the main mission file.
