### ISSUE TITLE
Add base ambience to remaining bases.

### ISSUE THREAD

**Issue by jerkinmerkin** [Task-Force-Red/Operation-Python#7]
This is one huge thing that you guys can help on.  So far I’ve added ambience to the following areas: Prozakhar Forward Air Base, COP Weasel, and COP Gillette.  I still need to add ambiance to FOB Bronco, COP Pilgrim, COP Beagle, COP Viking, and COP Vampire.  I would like COP Viking and COP Vampire to be SOF outposts.   Please look at how I set ambience up at the completed outposts to get an idea of how I picture the base ambiance.

**Comment by jerkinmerkin** [comment]
@Jmaster9999 , @Jebudiah , @Scotty-Z this sounds right up your alley if you can lend a hand.

**Comment by Will-Nichols** [comment]
What types are you looking for with this?

**Comment by jerkinmerkin** [comment]
Completed COP Vampire.  @Will-Nichols just take a look at what I have already in game to get an idea of what I mean by "ambiance"

**Comment by jerkinmerkin** [comment]
COP Viking Complete.

**Comment by jerkinmerkin** [comment]
COP Beagle, COP Pilgrim, and COP Bronco complete.  All bases complete.
