### ISSUE TITLE
Update Raven UAV to a vehicle for the mission

### ISSUE THREAD

**Issue by jerkinmerkin** [Task-Force-Red/Operation-Python#8]
As the title says, I want to create a config to add the Raven UAV to the USM ALICE Backpack for SOT.  I did it to a different backpack on OP Righteous Thunder so I know it can be done... I just gotta get off my ass and do it.

**Comment by jerkinmerkin** [comment]
@LewisSO will look into improving up the Raven

**Comment by Will-Nichols** [comment]
Honestly would really like to see us get away from using the Raven as it doesn't always do right and people look funny with a set of wings sticking out of their ass when they "disassemble" the thing. Plus it creates problems with performance when sent miles ahead of the units and left out there.

**Comment by jerkinmerkin** [comment]
If we're all good with the satellite mod, I don't really see the need for this, unless we want both.  Should i close it?
